// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using SoftwareFactory.Infrastructure.Persistence;

#nullable disable

namespace SoftwareFactory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SoftwareFactoryDbContext))]
    [Migration("20260916214423_ArtifactContentSchemaVersion")]
    partial class ArtifactContentSchemaVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoftwareFactory.Domain.Brain.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Citation")
                        .HasColumnType("text")
                        .HasColumnName("citation");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_chunk");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_chunk_embedding_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_chunk_tenant_id");

                    b.HasIndex("SourceDocumentId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_chunk_source_document_id_sequence");

                    b.ToTable("chunk", null, t =>
                        {
                            t.HasCheckConstraint("ck_chunk_sequence", "sequence >= 0");
                        });
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Brain.SourceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("SourceReference")
                        .HasColumnType("text")
                        .HasColumnName("source_reference");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_source_document");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_source_document_tenant_id");

                    b.ToTable("source_document", null, t =>
                        {
                            t.HasCheckConstraint("ck_source_document_size_bytes", "size_bytes >= 0");

                            t.HasCheckConstraint("ck_source_document_state", "state IN ('pending', 'indexed', 'failed')");
                        });
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Finops.LlmCall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CacheReadTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cache_read_tokens");

                    b.Property<int>("CacheWriteTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cache_write_tokens");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_llm_call");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_llm_call_job_id");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_llm_call_tenant_id_created_at");

                    b.ToTable("llm_call", null, t =>
                        {
                            t.HasCheckConstraint("ck_llm_call_non_negative", "input_tokens >= 0 AND output_tokens >= 0 AND cache_read_tokens >= 0 AND cache_write_tokens >= 0 AND latency_ms >= 0 AND cost >= 0");
                        });
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Platform.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("FailedAccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_access_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("text")
                        .HasColumnName("two_factor_secret");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_app_user_tenant_id_normalized_email");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Platform.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_event");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_audit_event_actor_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_event_tenant_id_occurred_at");

                    b.ToTable("audit_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_event_action", "action IN ('login_succeeded', 'login_failed', 'lockout', 'refresh_reuse_detected', 'logout', 'password_changed', 'artifact_created', 'artifact_updated', 'artifact_state_changed', 'artifact_deleted')");

                            t.HasCheckConstraint("ck_audit_event_actor_type", "actor_type IS NULL OR actor_type IN ('human', 'agent')");
                        });
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Platform.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Phase")
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percent");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_job");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_job_tenant_id");

                    b.HasIndex("AvailableAt", "CreatedAt")
                        .HasDatabaseName("ix_job_claimable")
                        .HasFilter("state IN ('pending', 'running')");

                    b.ToTable("job", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_state", "state IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Platform.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_token_family_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.HasIndex("TenantId", "TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_token_tenant_id_token_hash");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Platform.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_slug");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Platform.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_role");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_role_tenant_id");

                    b.HasIndex("UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_user_role_user_id_role");

                    b.ToTable("user_role", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_role_role", "role IN ('admin', 'functional', 'architect', 'qa', 'compliance', 'reader')");
                        });
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Project.SoftwareProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_project_tenant_id_name");

                    b.ToTable("project", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_state", "state IN ('active', 'archived')");
                        });
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Traceability.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("current_version");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_artifact");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_artifact_project_id");

                    b.HasIndex("ProjectId", "State")
                        .HasDatabaseName("ix_artifact_alive")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId", "ProjectId", "Type")
                        .HasDatabaseName("ix_artifact_tenant_id_project_id_type");

                    b.ToTable("artifact", null, t =>
                        {
                            t.HasCheckConstraint("ck_artifact_current_version", "current_version >= 0");

                            t.HasCheckConstraint("ck_artifact_level", "level IN ('project', 'global')");

                            t.HasCheckConstraint("ck_artifact_score", "score IS NULL OR (score BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_artifact_state", "state IN ('draft', 'in_review', 'approved', 'frozen')");
                        });
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Traceability.ArtifactVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_type");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_artifact_version");

                    b.HasIndex("Content")
                        .HasDatabaseName("ix_artifact_version_content");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Content"), "gin");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_artifact_version_tenant_id");

                    b.HasIndex("ArtifactId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_artifact_version_artifact_id_number");

                    b.ToTable("artifact_version", null, t =>
                        {
                            t.HasCheckConstraint("ck_artifact_version_author_type", "author_type IN ('human', 'agent')");

                            t.HasCheckConstraint("ck_artifact_version_number", "number >= 1");

                            t.HasCheckConstraint("ck_artifact_version_schema_version", "schema_version >= 1");
                        });
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Traceability.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<Guid?>("ParentDecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_decision_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_decision");

                    b.HasIndex("ParentDecisionId")
                        .HasDatabaseName("ix_decision_parent_decision_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_decision_project_id");

                    b.HasIndex("TenantId", "ProjectId")
                        .HasDatabaseName("ix_decision_tenant_id_project_id");

                    b.ToTable("decision", null, t =>
                        {
                            t.HasCheckConstraint("ck_decision_author_type", "author_type IN ('human', 'agent')");

                            t.HasCheckConstraint("ck_decision_role", "role IN ('admin', 'functional', 'architect', 'qa', 'compliance', 'reader')");

                            t.HasCheckConstraint("ck_decision_state", "state IN ('recorded', 'pending', 'ratified', 'reverted')");

                            t.HasCheckConstraint("ck_decision_type", "type IN ('decision', 'out_of_role_note', 'ratification', 'reversion')");
                        });
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Traceability.Relation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_relation");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_relation_source_id");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_relation_target_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_relation_tenant_id");

                    b.HasIndex("SourceId", "TargetId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_relation_source_id_target_id_type");

                    b.ToTable("relation", null, t =>
                        {
                            t.HasCheckConstraint("ck_relation_created_by_type", "created_by_type IN ('human', 'agent')");

                            t.HasCheckConstraint("ck_relation_not_reflexive", "source_id <> target_id");
                        });
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Brain.Chunk", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Brain.SourceDocument", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chunk_source_document_id");

                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chunk_tenant_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Brain.SourceDocument", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_source_document_tenant_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Finops.LlmCall", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Platform.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_llm_call_job_id");

                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_llm_call_tenant_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Platform.AppUser", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_user_tenant_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Platform.AuditEvent", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_event_tenant_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Platform.Job", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_job_tenant_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Platform.RefreshToken", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_tenant_id");

                    b.HasOne("SoftwareFactory.Domain.Platform.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_user_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Platform.UserRole", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_tenant_id");

                    b.HasOne("SoftwareFactory.Domain.Platform.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Project.SoftwareProject", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_tenant_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Traceability.Artifact", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Project.SoftwareProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_artifact_project_id");

                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_artifact_tenant_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Traceability.ArtifactVersion", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Traceability.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artifact_version_artifact_id");

                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_artifact_version_tenant_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Traceability.Decision", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Traceability.Decision", null)
                        .WithMany()
                        .HasForeignKey("ParentDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_decision_parent_decision_id");

                    b.HasOne("SoftwareFactory.Domain.Project.SoftwareProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_decision_project_id");

                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_decision_tenant_id");
                });

            modelBuilder.Entity("SoftwareFactory.Domain.Traceability.Relation", b =>
                {
                    b.HasOne("SoftwareFactory.Domain.Traceability.Artifact", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relation_source_id");

                    b.HasOne("SoftwareFactory.Domain.Traceability.Artifact", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relation_target_id");

                    b.HasOne("SoftwareFactory.Domain.Platform.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relation_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
